[package]
name = "faucet"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
types = { path = "../types" }
crypto = { path = "../crypto" }
rpc = { path = "../rpc" }
storage = { path = "../storage" }
thiserror.workspace = true
serde_json = "1"
ureq = { version = "2", default-features = false, features = ["json"] }

[dev-dependencies]
network = { path = "../network" }
node = { path = "../node" }
consensus = { path = "../consensus" }
execution = { path = "../execution" }
mempool = { path = "../mempool" }
state = { path = "../state" }
tokio.workspace = true
blst = "0.3"
