[package]
name = "crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
blake3.workspace = true
ed25519-dalek.workspace = true
blst.workspace = true
curve25519-dalek.workspace = true
sha2.workspace = true
rand.workspace = true
ark-bls12-381.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-serialize.workspace = true

[dev-dependencies]
hex.workspace = true
rand.workspace = true
